### ISSUE TITLE
Use Knex migrations

### ISSUE THREAD

**Issue by ttencate** [mkalam-alami/alakajam#17]
Suppose version 2 adds a table T, and version 3 adds a foreign key to table U that references T, then we can't upgrade U from version 1 to 3 in one go. Rather, we must first upgrade both T and U to version 2, and then both T and U to version 3.

In the same vein, if table V is added in version 2 and a foreign key into V is added to table U also in version 2, then we must ensure that these upgrades happen (and un-happen) in the right order. So simply going by the ordering in `models/index.js` might not always be sufficient.

Maybe we should just use [Knex's migrations system](http://knexjs.org/#Migrations) instead? I also just noticed a section on [seed files](http://knexjs.org/#Seeds-CLI). I'm new to Knex and Bookshelf, so I don't know whether these will do what we want.

**Comment by mkalam-alami** [comment]
I've read good things about Knex's migrations (some people only use it for that actually). I admit I haven't taken the time to look at it in detail, until then I've just tweaked the upgrade algo to work version by version :P

**Comment by mkalam-alami** [comment]
Knex migrations turned out very simple to work with. The server now launches a knex upgrade every startup, but we can also manipulate things on the command-line to deal with rollbacks for instance.
