### ISSUE TITLE
Theme voting system

### ISSUE THREAD

**Issue by mkalam-alami** [mkalam-alami/alakajam#20]
## Iteration 1: Theme submission/voting

- [x] Theme model: id/event_id/user_id/score/notes/flags/status[=active/out/flagged/shortlist]/ts
- [x] Theme vote model: id/theme_id/event_id/user_id/score/ts
- [x] Event Details model: theme_count, active_theme_count
- [x] Make it possible to submit up to 3 themes
- [x] AJAX API: Fetch a random, not ours, not rated theme
- [x] AJAX API: Vote on a theme (+1 or -1)
- [x] Make it possible to vote on a theme

## Iteration 2: Progress/Results

- [x] Display the history of the last 30 votes & let the user change them
- [x] Handle duplicates
- [x] Let the user know how many theme she rated
- [x] Refresh the event details info on each theme submission creation/deletion
- [x] Every 10 votes, eliminate the lowest ranking one (it must have at least 5 notes)
- [x] Display a stack progress bar showing the theme_count/active_theme_count/fixed shortlist with the goal to make the active_theme_count = fixed shortlist.
- [x] Show theme voting stats
- [x] Let admins set event status_theme = 'results'
- [x] If event status_theme = 'results', show instead the 10 highest scoring themes, making the winning one stand out.

## Iteration 3: Shortlist voting/Security

- [x] Let admins set event status_theme = 'shortlist'. If set, pick the 10 highest scoring themes & mark them as shortlist. All the other ones must be marked as out.
- [x] If event status_theme = 'shortlist', show the 10 highest scoring themes, let the user rank them and save the changes (yields a score from 1 to 10 replacing the current user vote). Use https://github.com/RubaXa/Sortable
- [x] Show the submitted theme status (active/out/shortlist), show its score (out in {{notes}} rounds) if its out
- [x] Prevent removing a theme that is out or shortlisted
- [x] Make sure we prevent voting/shortlisting when not appropriate
- [x] Let admins ban themes

## Iteration 4: Polish

(fill this as we find tweaks to make)

## Submission/Voting phase
![1](https://user-images.githubusercontent.com/694508/28995444-88410364-79e9-11e7-9bbc-c0de570c8177.png)

## Shortlist phase
![2](https://user-images.githubusercontent.com/694508/28995445-88423252-79e9-11e7-9f33-c1e74dddd1ee.png)

## Results phase
![3](https://user-images.githubusercontent.com/694508/28995446-8843542a-79e9-11e7-84af-78d13601875b.png)

**Comment by ttencate** [comment]
Duels! Excellent! I was about to suggest that :) For the shortlist phase, maybe we could be different from LD (read: better) as well, e.g. stack ranking?

**Comment by mkalam-alami** [comment]
Currently I tend to be in favor of scrapping the shortlist voting altogether, mostly because:

* The voting phase could use to be simpler and especially much faster (< 1 week, for better hype-building)
* I feel like final rounds of voting tend to lead to some disappointment, i.e. people see their favorite themes disappear/not get chosen despite their votes. With stack ranking that would mean the majority of voters won't see their top pick get elected.

In its currently planned form, the read-only shortlist is more "here are the 10 themes people liked the most! the winning one is already chosen and is in this list, which one do you think it is? which ones would you prefer?" Which still builds the hype while hopefully improving on the mentioned issues.

Discussion welcome!

**Comment by ttencate** [comment]
Suggested by sorceress: the 1HGJ theme selection system.

- we can submit themes at any time
- we can vote on themes at any time
- one of the top 5 scoring is selected at random as the theme for the current game jam
- old and low scoring themes get periodically removed from the list

Pros:

- no need to go through the same pool of themes every time, or regenerate that pool from scratch

Cons:

- less hype building

Maybe a hybrid? A week before the jam, take the current top N and do some other kind of voting.

**Comment by mkalam-alami** [comment]
Given there seems to be a negative history about "duel voting", I made a little script to see whether it's really as frustrating as it seems: [Duel voting test](http://marwane.kalam-alami.net/tmp/slaughter-duels-test/)

Indeed it seems to be more tiring that the good old +1/-1 system (maybe also it's because I'm tired as I write this though :P)

**Comment by ttencate** [comment]
Thanks for mocking it up! I agree, it feels more tiring. Wonder if the probable reduction in the number of votes actually lead to worse data, but I'm happier to just run with the old approach now.

I still think a stack rank could work well for the final round(s) though ([instant-runoff voting](https://en.wikipedia.org/wiki/Instant-runoff_voting)). You tend to think more carefully in that phase anyway.

**Comment by mkalam-alami** [comment]
Ok let's scrap the duel thing then. In the end it was just a specific way to dispense +1s/1s, so the merged slaughter/voting system still stands.

I also like the instant-runoff idea, i.e. picking the most consensual theme. If we do that, a single round sounds good enough.

**Comment by mkalam-alami** [comment]
Releasing this issue for now as we have a minimal feature working. Will continue once game voting/results are ready.
