### ISSUE TITLE
Store game platform information

### ISSUE THREAD

**Issue by mkalam-alami** [mkalam-alami/alakajam#31]
> Requires #28

- [x] Make the user choose the title from a dropdown instead of just plain text (**Play**: Windows/Linux/Mac/Web - **Other:** Sources, Soundtrack, Custom link), with the "Custom Link" option enabling a text field instead.
- [x] On the entry thumbnails, use the links info to display platform icons
- [x] Set up an `entry_platform` table (with one row per platform), and store platform info there upon entry save. `entry_platform` will be useful for the future search forms.

**Comment by Thrainsa** [comment]
Sorry but I don't really see what you want with the entry_platform table. 
Do you want that the entry links are linked directly to this table?

**Comment by mkalam-alami** [comment]
The `entry_platform` table as I'd see it would simply look like this:

* integer entry_id
* string platform

The idea is to leave the JSON in the entry table (for performance) but also duplicate the info so we can make games searchable by platform with SQL.

**Comment by mkalam-alami** [comment]
The last bullet point is done!
