### ISSUE TITLE
Support teams

### ISSUE THREAD

**Issue by mkalam-alami** [mkalam-alami/alakajam#36]
*EDIT: Polishing pass*

- [x] Merge the manage team page with the manage entry one since it now uses AJAX & stuff
- [x] Make the field appear dynamically & only if the entry is set to "Team"
- [x] Clear user roles manually when deleting an entry/post (follow-up to #93)
- [x] Handle the case where the entry is set back to Solo
- [x] Make the "category/manage team" fields read-only for non-owners (+ appropriate server checks)
- [x] Replace the "Delete" button for non-owners (it should not work anyway) with a "Leave team" button
- [x] Fix SQLite support (ILIKE)
- [x] Fix not being able to clear the team
- [x] Make the field fill the whole width
- [x] Display a warning if a user is about to clear his team (check + confirm dialog with JS upon Save)
- [x] Make it more clear that the first role cannot be deleted because he's the owner (maybe even put him outside the field?)
- [x] Make it more clear  (CSS+maybe message?) that some users cannot be added
- [x] Sort user roles for display
- [x] Server-side check for changing the game category

----------------

## Entry edit page

- [x] Add solo/team toggle in entry edit form, with a tooltip saying that the team can be managed after saving (model field: `entry.category`)

## Entry view page

- [x] List user roles on the entry sidebar (use and improve the `_macros-user.html > userThumb` macro styling
- [x] If the entry is team-based show in the entry sidebar a "Manage team" link leading to a separate page

## Team management page

- [x] List the entry user roles 
- [x] AJAX API that renders only one user, by its name (in HTML)
- [x] Add username field + button to let users add new user roles in Ajax (not saved yet).
- [x] Add "Save changes" button to apply team changes. All non-owner user roles are cleared then rebuilt from the form contents. Users are added with a "write" permission. Owner cannot be changed.
- [x] Add "Restore" button which just refreshes the page
- [x] Add a little button on each user role (except the owner) to remove them in JS
- [x] Prevent users from joining multiple teams (if only because of UI limitations)
- [x] Let people leave a game they have been added to

## Tests

- [x] Check that non-owner users can edit the entry
- [x] Check that non-owner users are listed on entry thumbs
- [x] Check that non-owner users can make posts related to the entry
- [x] Check that non-owner users have the entry on their profile

**Comment by coxm** [comment]
Is it possible to make a post relate to an entry? Seems the `entry_id` column is always null on my dev database and I couldn't find a way of associating the post with an entry.

Also it seems everyone on a team can edit everything (except removing the owner; this is impossible regardless of the user). Is this the desired behaviour?

**Comment by mkalam-alami** [comment]
> Is it possible to make a post relate to an entry? Seems the entry_id column is always null on my dev database and I couldn't find a way of associating the post with an entry.

Maybe there's a bug? Right now it's supposed to be automatic, i.e. just post to an event, and if you have an entry it will be attached (see post-controller.js around l260). The only minor issue is that posts made before creating the entry need to be edited + saved for the entry to be attached.

> Also it seems everyone on a team can edit everything (except removing the owner; this is impossible regardless of the user). Is this the desired behaviour?

It would be bes to only have the owner manage the team yeah. I'll look into it.
