### ISSUE TITLE
JSON API

### ISSUE THREAD

**Issue by mkalam-alami** [mkalam-alami/alakajam#67]
In the short term it would be useful for IRC bots like @pta2002's PAIB.

- [x] Featured: Get info on the currently featured event
- [x]  Event: Get event info including a list of all its games
- [x] Entry: Get detailed info on an entry
- [x] User: Get detailed info on a user
- [x] Put a link to the API somewhere
- [x] Bonus: Format the event countdown (requires parts of #68)
- [x] Use a Node module like **AdamPflug/express-brute** for limiting API calls
- [x] Configure express-brute for the whole site - especially login/register forms - while we're at it

**Comment by pta2002** [comment]
I have some API endpoint ideas

 - `/api/:user/latestEntry`: self explanatory, returns latest entry
 - `/api/:user/posts/`: returns user posts
 - `/api/posts`: returns latest posts posts, with optional page query
 - `/api/posts/:post`: returns specific post

**Comment by mkalam-alami** [comment]
Ok, feel free to implement them! I'd just tweak the user endpoints to this:

- /api/**user/**:user/latestEntry
- /api/**user/**:user/posts

**Comment by mkalam-alami** [comment]
Closing the issue since the initial todo-list is done. 

Why not add the post-related endpoints, if we end up doing those we can create a separate issue.
