### ISSUE TITLE
Mentions are case-sensitive

### ISSUE THREAD

**Issue by mkalam-alami** [mkalam-alami/alakajam#70]

**Comment by dollarone** [comment]
Ah, this is why I did toLowercase() on usernames before putting them in cache - then you can toLowercase() any mention and put it in the relevant user cache. 

See/compare 
https://github.com/mkalam-alami/alakajam/blob/e418b00a94d8ecd53e0affbe3a01edeb010cae44/controllers/post-controller.js#L341
and
https://github.com/mkalam-alami/alakajam/blob/master/controllers/post-controller.js#L357
(And the previous paragraph as well)

**Comment by mkalam-alami** [comment]
Yeah it seems I have broken this when polishing the API, thanks for the pointers.

**Comment by dollarone** [comment]
Hmm yeah that looks like it should work then!

**Comment by dollarone** [comment]
Potentially need it in the user() method as well?

**Comment by mkalam-alami** [comment]
Apparently I never made the query itself insensitive: https://github.com/mkalam-alami/alakajam/commit/c53803516451b3f10abb54cc7218f9d9f80a044c

Looks good now!
