### ISSUE TITLE
URL redirections

### ISSUE THREAD

**Issue by mkalam-alami** [mkalam-alami/alakajam#71]
Just some routing tweaks to avoid 404 errors when people fiddle with the URLs:

- [x] Redirect /user to /people 
- [x] Redirect /post to /posts
- [x] Make /dashboard display /dashboard/feeds
- [x] When displaying /&lt;event&gt;/ (with the slash at the end), the "Posts" tab should be highlighted

**Comment by pta2002** [comment]
As for the last point, I think that the problem is that when the check on whether to make the link active or not, we're only checking for the version without the /, shouldn't be very hard to solve. (It happens on every page by the way)
