### ISSUE TITLE
Theme selection doesn't work when the URL has a trailing /

### ISSUE THREAD

**Issue by pta2002** [mkalam-alami/alakajam#83]
If I go to /:eventName/themes/, the theme selection widget won't show up.

![with trailing slash](https://user-images.githubusercontent.com/7443916/29433280-6fcb8dfc-8396-11e7-9751-2d0e5ffa0b87.png)

versus

![without trailing slash](https://user-images.githubusercontent.com/7443916/29433292-77e434ee-8396-11e7-98ef-6e648d06e6e7.png)

**Comment by pta2002** [comment]
Traced it back to line 227 of view-events-theme.html

```js
$.getJSON('./ajax-find-themes', function (data) {...})
```

This works fine when there is no trailing slash (the url is `:eventName/themes`), as it will query `:eventName/ajax-find-themes`. However, if we add a trailing slash (url is `:eventName/themes/`), it will instead query `:eventName/themes/ajax-find-themes`.

I can see two simple ways of fixing this:

 - Make it so `:eventName/themes/ajax-find-themes` behave the same as `:eventName/ajax-find-themes` (hackier, but works)
 - Add the correct `ajax-find-themes` URL to the context

**Comment by pta2002** [comment]
Fixed by changing `./ajax-find-themes` to `{{ buildUrl(event, 'event', 'ajax-find-themes') }}`.

**Comment by mkalam-alami** [comment]
The fix looks good, thanks!
