### ISSUE TITLE
Can't include database (hence models) in tests

### ISSUE THREAD

**Issue by coxm** [mkalam-alami/alakajam#96]
Importing `core/db.js` in tests, apparently before or after the `require('./support/test-server')` call, breaks the testing environment. Specifically, when `createKnexInstance` is called, the config has been reverted to the development config. This results in the development database being filled with fake test data.

**Comment by mkalam-alami** [comment]
Things work for me as long as I `require('../core/db')` inside the tests, i.e. inside the `it()` function like the other services.

**Comment by coxm** [comment]
Ah you're right, it does! I was including in the `describe()` call instead. Perhaps we can make it less delicate after the jam but this will work fine for now :)
